### ISSUE TITLE
Cannot use -u and --node-labels together

### ISSUE THREAD

**Issue by paulbdavis** [robscott/kube-capacity#22]
Trying to use these together results in the following error message:

```
 % kubectl resource-capacity --node-labels 'kubernetes.io/role=node' -u                                                           
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x10cf0c5]

goroutine 1 [running]:
github.com/robscott/kube-capacity/pkg/capacity.buildClusterMetric(0xc0001324d0, 0xc000269ab0, 0xc000492d20, 0xc0001344d0, 0x0, 0x17, 0x0)
	/usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/pkg/capacity/resources.go:97 +0x4c5
github.com/robscott/kube-capacity/pkg/capacity.FetchAndPrint(0x1010000, 0x0, 0x0, 0x7ffd49634e63, 0x17, 0x0, 0x0, 0x0, 0x0, 0x136a805, ...)
	/usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/pkg/capacity/capacity.go:53 +0x286
github.com/robscott/kube-capacity/pkg/cmd.glob..func1(0x20ca900, 0xc00038c450, 0x0, 0x3)
	/usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/pkg/cmd/root.go:49 +0x21d
github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra.(*Command).execute(0x20ca900, 0xc00003a090, 0x3, 0x3, 0x20ca900, 0xc00003a090)
	/usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x20ca900, 0xc00041bf68, 0x10e5cae, 0x20ca900)
	/usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/vendor/github.com/spf13/cobra/command.go:800
github.com/robscott/kube-capacity/pkg/cmd.Execute()
	/usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/pkg/cmd/root.go:79 +0x32
main.main()
	/usr/local/google/home/robertjscott/go/src/github.com/robscott/kube-capacity/main.go:22 +0x20
```

Using kops deployed kubernetes on AWS, installed this plugin via krew

**Comment by robscott** [comment]
Hey @paulbdavis, thanks for reporting this! This has been fixed in 0.3.2, but unfortunately I haven't had the time to add that release to Krew yet. I'll try to make some time for that relatively soon, but in the meantime, the binaries on the releases page or a brew install should have a fix for you.

**Comment by robscott** [comment]
I'm going to close this for now, let me know if the issue shows up again, thanks!

**Comment by fcantournet** [comment]
@robscott version 0.3.3 still isn't pulished on krew AFAICT ? any blockers ?
